# ロールのデフォルト設定
---
ruby_version: 2.1.1
passenger_version: 4.0.41
host_name: localhost
passenger_max_pool_size: 10
passenger_min_instances: 5
rails_apps:
  - name: service
    rails_env: development
  - name: admin
    rails_env: development
