- name: be sure apache httpd are installed
  yum: name={{item}} enablerepo=epel state=installed
  with_items:
    - httpd
    - httpd-devel
    - mod_ssl
  tags: apache

- name: configure apache server-status
  lineinfile: src=httpd.conf dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644 backup=yes insertafter=EOF
  tags: apache

- name: configure log rotate
  shell: sed -i 's/missingok/missingok\n    daily\n    dateext/' /etc/logrotate.d/httpd
  tags: apache

- name: configure monit
  copy: src=httpd.monit.conf dest=/etc/monit.d/httpd.conf owner=root group=root mode=0744
  tags: apache
